### PR TITLE
Remove findbugs plugin

### PR DESCRIPTION
**Pull request by alxsap**
Do we really need the findbugs plugin? It reached end of life and has been replaced by the warnings-ng plugin.

> This plugin reached end-of-life.
> All functionality has been integrated into the Warnings Next Generation Plugin and the Static Analysis Model and Parsers Library.
> https://github.com/jenkinsci/findbugs-plugin/blob/master/README.md

### CODE REVIEW

**Comment by romanisb** [comment]
BTW, apparently there is also a plugin missing. Should be the `performance` plugin.

**Comment by srinikitha09** [comment]
Not sure removing this plugin would lead into an issue even though it has been integrated into warnings-ng plugin. However, needs to be tested. 

Currently, I am testing  v39 for cloud sdk pipeline which uses `analysis collector` plugin. This is also missing in our case. This [plugin ](https://plugins.jenkins.io/analysis-collector/)has also been integrated into warnings plugin but still the pipeline fails.

**Comment by alxsap** [comment]
> BTW, apparently there is also a plugin missing. Should be the `performance` plugin.

What fails w/o the plugin?

**Comment by romanisb** [comment]
> What fails w/o the plugin?
The PerformanceTestStage of the cloud-sdk-pipeline configured to use jMeter.

**Comment by alxsap** [comment]
Last findbugs plugin changes, 2 years ago, it is dead. The plugin has an [indirect dependency](https://github.com/findbugsproject/findbugs/blob/release-2.0.3/findbugs/pom.xml#L192) to dom4j:1.6.1 from 2005.

**Comment by alxsap** [comment]
> > What fails w/o the plugin?
> 
> The PerformanceTestStage of the cloud-sdk-pipeline configured to use jMeter.

Why didn't we see this during tests? Our automated tests should be tuned to find such cases...

**Comment by alxsap** [comment]
Regarding performance plugin: https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/42

**Comment by srinikitha09** [comment]
> Last findbugs plugin changes, 2 years ago, it is dead. The plugin has an [indirect dependency](https://github.com/findbugsproject/findbugs/blob/release-2.0.3/findbugs/pom.xml#L192) to dom4j:1.6.1 from 2005.

Is there any issue with `dom4j:1.6.1`?

**Comment by alxsap** [comment]
Yes, 2 vulnerabilities.
Even in 2.1.1 one is left and we have to switch to dom4j 2.1.3.

**Comment by srinikitha09** [comment]
> > > What fails w/o the plugin?
> > 
> > 
> > The PerformanceTestStage of the cloud-sdk-pipeline configured to use jMeter.
> 
> Why didn't we see this during tests? Our automated tests should be tuned to find such cases...

Basically, to run actual performance tests exec, step config should be added ex: [here](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/v35/resources/default_s4_pipeline_environment.yml#L64). We never added this config as it is already there in the default environment. But, seems like it is ignored.

**Comment by srinikitha09** [comment]
> Yes, 2 vulnerabilities.
> Even in 2.1.1 one is left and we have to switch to dom4j 2.1.3.
> 
> And since the findbugs plugin is end-of-life we will not get any plugin updates.

Then, we can test this change in one of our test clusters.

**Comment by alxsap** [comment]
continue in https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/44

**Pull request closed without merging**
